pages:
  stage: deploy
  script:
    - mkdir public
    - cp *.html public/
    - cp *.css public/
    - cp *.png public/
    - cp -r images public/
  artifacts:
    paths:
      - public
  only:
    - master
